{{- if .Values.accumulo.manager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "accumulo.fullname" . }}-manager
  labels:
    {{- include "accumulo.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
  {{- with .Values.global.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 9999
    targetPort: client
    protocol: TCP
  - name: replication
    port: 10001
    targetPort: replication
    protocol: TCP
  selector:
    {{- include "accumulo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: manager
{{- end }}