apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "accumulo.fullname" .}}-config
  labels:
    {{- include "accumulo.labels" . | nindent 4 }}
    app.kubernetes.io/component: alluxio
data:
  accumulo.properties: |
    # Apache Accumulo Configuration for Kubernetes
    instance.volumes={{ .Values.accumulo.instance.volumes }}
    instance.zookeeper.host={{ include "accumulo.zookeeperHosts" . }}
    instance.secret={{ .Values.accumulo.instance.secret }}
    tserver.memory.maps.native.enabled=true
    manager.recovery.delay=10s
    manager.lease.recovery.waiting.period=5s
    tserver.port.search=true
    tserver.hold.time.max=5m
    tserver.memory.maps.max=1G
    monitor.port.client=9995
    monitor.ssl.port=9995
    gc.cycle.start=30s
    gc.cycle.delay=5m
    compactor.max.open.files=100
    general.rpc.timeout=120s
    tserver.scan.timeout.enable=true
    tserver.scan.timeout.max=5m
    general.vfs.context.class.name=org.apache.accumulo.core.spi.fs.VolumeChooserEnvironment
    general.vfs.cache.dir=/tmp/accumulo-vfs-cache
